### PR TITLE
Decorator to memoize function outputs to a file

### PR DESCRIPTION
**Pull request by adamwight**
This can become more sophisticated in later work.  One nice improvement would be to support both .csv and .ndjson .

### CODE REVIEW

**Comment by adamwight** [comment]
Self-merging so we can move forward with more project-relevant details.

**Review by Abhishek02bhardwaj — COMMENTED** [review]
Ohkay, now I understand the decorator being used. It is really helpful. Do you think we can use a decorator to save our outputs at each step of data extraction process. Like if we do the extraction in steps then at every step we can keep the data in its current form.

**Comment by adamwight** [comment]
> Do you think we can use a decorator to save our outputs at each step of data extraction process. Like if we do the extraction in steps then at every step we can keep the data in its current form.

My current thinking is that memoized and non-memoized public accessors can exist side-by-side, for example in [content_translation_stats](https://github.com/outreachy-translation-imbalances/translation-stats-lib/blob/main/content_translation_stats.py) .  What about these criteria for deciding when to save an output:
* Is this output expensive to calculate (let's say more than 1 second of network or processing)?
* Will an external tool (anything but a Python script, so can't call a module function) be reading this output?

**Comment by adamwight** [comment]
I added this documentation as a draft in #6—please review and make changes.

**Pull request merged**
